language: python
python:
  - 3.6
env:
  global:
    - REMOTE_REPO_OWNER='AgenciaImplementacion'
    - REMOTE_REPO_NAME='Asistente-LADM_COL'
install:
  - cat packages.txt | xargs sudo apt-get install
  - pip install -r requirements.txt

script:
  - ./generate.sh

after_success:
  echo 'Finished!'

before_deploy:
  - ./deploy.sh

deploy:
  skip_cleanup: true
  provider: releases
  api_key: ${GH_ADMINAGENCIAIMPL_ACCESS_TOKEN}
  file: [asistente_ladm_col_docs_es.zip, asistente_ladm_col_docs_en.zip]
  on:
    repo: AgenciaImplementacion/Asistente-LADM_COL-docs
    tags: true
