language: python
python:
  - 3.6
env:
  global:
    - REMOTE_REPO_OWNER='AgenciaImplementacion'
    - REMOTE_REPO_NAME='Asistente-LADM_COL'
install:
  - pip install -r requirements.txt

script:
  - ./generate.sh

after_success:
  - ./deploy.sh
